name: GENX
favicon: null
layout_spectrum: 0.33378
typography_spectrum: 0.42353
title: Lowest Cruise prices Always!
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#060606'
    - '#40307a'
    - '#a61f2e'
    - '#858a8d'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5217611182015389
  rhythmicContrast: 0.813452631700784
purpose: []
